language: java
jdk:
  - openjdk8
  - oraclejdk8

sudo: false
install: true

branches:
  only:
  - travislab

script:
  - ./webapp/gradlew build

after_success:
  - mkdir codedeploy
  - pwd
  - zip -r csye6225-web-app-$TRAVIS_JOB_NUMBER.zip webapp/build/libs/exploded/ROOT.war infrastructure/aws/codedeploy/appspec.yml
  - ls -al
  - mv csye6225-web-app-$TRAVIS_JOB_NUMBER.zip codedeploy/
  - ls -al
  - pwd
  - cd codedeploy
  - ls -al
  - pwd
  - cd ..
  - pwd

deploy:
  - provider: s3
    localdir: codedeploy
    bucket: code-deploy.csye6225zzy.com
    region: us-east-1
    skip_cleanup: true
    access_key_id: $access_key_id
    secret_access_key: $secret_access_key
    on:
      branch: travislab
notifications:
  email:
    recipients:
      - guo.bei@husky.neu.edu
      - zhu.zheny@husky.neu.edu
      - zhou.yiy@husky.neu.edu
    on_success: always
    on_failure: never
