language: java
jdk:
  - openjdk8
  - oraclejdk8

sudo: false
install: true

branches:
  only:
  - travislab

script:
  - ./webapp/gradlew build

after_success:
  - mkdir codedeploy
  - pwd
  - zip -r csye6225-web-app-$TRAVIS_JOB_NUMBER.zip build/libs/exploded/ROOT.war infrastructure/aws/codedeploy/appspec.yml
  - ls -al
  - mv csye6225-web-app-$TRAVIS_JOB_NUMBER.zip codedeploy/
  - ls -al
  - pwd
  - cd codedeploy
  - ls -al
  - pwd
  - cd ..
  - pwd
notifications:
  email:
    recipients:
      - guo.bei@husky.neu.edu
      - zhu.zheny@husky.neu.edu
      - zhou.yiy@husky.neu.edu
    on_success: always
    on_failure: never
